### ISSUE TITLE
WHY

### ISSUE THREAD

**Issue by AkeBoss-tech** [notrealn/french-revolution-project#1]
Tell me, how did you feel while writing all your HTML on ONE line? Cause I felt really bad trying to read it.

**Comment by notrealn** [comment]
dude...... its auto generated from webpack

**Comment by notrealn** [comment]
you think i wrote those garbage js files that are 1 line and have var names that are 1 letter long

**Comment by notrealn** [comment]
how tf does this not look like auto generated stuff
![image](https://user-images.githubusercontent.com/56411504/102645598-b4a6d480-4130-11eb-9bed-294b88639115.png)

**Comment by wiisportsresort** [comment]
wdym i always use one letter long variable names and call my main file `main.0c89117530b6b55c010c.js`
